# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 3
updates:
  # 1. Python Backend Dependencies
  - package-ecosystem: "pip"
    directory: "/weather-app" # Location of requirements.txt
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    groups:
      python-dependencies:
        patterns:
          - "*" # Groups all python updates into one PR

  # 2. TypeScript Frontend Dependencies
  - package-ecosystem: "npm"
    directory: "/web" # Location of package.json as per architecture
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    groups:
      python-dependencies:
        patterns:
          - "*" # Groups all python updates into one PR

  # 3. Docker Dependencies
  - package-ecosystem: "docker"
    directory: "/weather-app" # Location of your Dockerfile/docker-compose.yml
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    groups:
      python-dependencies:
        patterns:
          - "*" # Groups all python updates into one PR
